### ISSUE TITLE
没有自适应

### ISSUE THREAD

**Issue by ianhhhhhhhhe** [stephenLYao/hexo-theme-fresh#1]
banner-image 建议放到 nav 里比较方便处理
nav 没有设置居中，浏览器拉伸会导致 banner-image 覆盖 nav 里的内容
nav 高度最好能和图片底部高度对其，这样就不会导致浏览器宽度减小到图片宽度以内时，图片下方出现空白

**Comment by stephenLYZ** [comment]
@IanPeverell 加上自适应了 :) 然后移动端也修复了 😄  谢谢支持
